site_name: Commentaires
site_url: https://denisshragin.github.io/comments/
nav:
  - Home: 'index.md'
  - Commentaires réception: 'reception.md'
  - Commentaires chimie: 'chemistry.md'
  - Commentaires inter-paramètres: 'inter_param.md'
  - Commentaires autres: 'comments.md'
  - Commentaires de hors-normes: 'hors_normes.md'
theme: 
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - content.code.copy
copyright: Copyright &copy; 2024  Denis Shragin

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
#plugins:
#  - offline:
#      enabled: !ENV [OFFLINE, false]

